
name: CSV file valid record
on:
  push:
    branches:
      - main
jobs:
      validate-file:
          runs-on: ubuntu-latest
          steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: run validate employee
              run:  python validata_emp.py

            - name: move data to target 
              run: echo 'move data'
